---
title: "Rasam"
date: 2023-12-24T23:49:38-08:00
draft: false
---


* Rasam

** Prep
- 1/3 cup toor dal



- 1 tbsp tamarind paste
- roughly 5 sprigs curry leaves
- 1-2 tomatoes, chopped or quartered


- 1-2 tsp each of asafoetida, turmeric
- This ratio of spices = 1 red chilli powder : 1.5 coriander : 2 cumin : 1 black pepper. How much of
  each you add is based on personal preference. Mine is at least 3 tsp of rcp.
- cilantro, chopped


The measurements of spices here are ultimately based on personal preference.


** Execute

1. Cook toor dal in instant pot. Roughly a 1:3 dal:water ratio.
2. Soak 1 tbsp of puli (tamarind) paste in water for about 10-15 minutes.
3. Set the water on stove, and add chopped tomatoes and curry leaves. Optionally, can add garlic cloves. Bring this water to a boil.
4. Add in asafoetida, turmeric, salt to taste.
5. Add in red chilli powder, coriander, cumin, black pepper. 
6. Allow the spiced water to boil. Add the cooked toor dal in small increments, until the preferred thickness is achieved.
7. Let boil for another 10-15 minutes, and add chopped cilantro. Add salt to taste. 
