name: Build site and deploy to GitHub Pages

on:
  push:
    branches:
      - master
    paths:
      - 'content/**'
      - 'build.sh'
      - '.github/workflows/build.yaml'

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Make build script executable
        run: chmod +x ./build.sh

      - name: Run build script
        run: ./build.sh

